### PR TITLE
Pass error as 1st pram of callback as per Node.js convention. (Plus other fixes.)

### PR DESCRIPTION
**Pull request by yangzai**
Bluebird, as well as many other modules, expects this convention in order to promisify the methods.

Reference: http://rob.conery.io/2012/02/25/nodejs-callback-conventions-and-your-app/

### CODE REVIEW

**Comment by kevincobain2000** [comment]
@yangzai  Thanks will look into it today.

**Comment by kevincobain2000** [comment]
ありがとう！

**Comment by yangzai** [comment]
Lol, I'm not Japanese but I do know a bit. Thanks for the merge too. Anyway you might consider incrementing the major version since the old parameters might not be compatible.

**Comment by kevincobain2000** [comment]
@yangzai sorry! your name is yang but I got carried away with ur DP!

**Pull request merged**
